# Generated by Django 6.0.6 on 2026-06-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionario',
            name='escala',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='escala',
            field=models.CharField(choices=[('likert4', 'Likert 0 a 3 (Nunca → Siempre)'), ('likert5', 'Likert 0 a 4 (Nunca → Casi siempre)'), ('sino', 'Si / No')], default='likert4', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='borrador', max_length=20),
        ),
    ]
