# Generated by Django 5.2.15 on 2026-06-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0003_asignacioncuestionario_respuestacuestionario_respuestapregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='subtipo',
            field=models.CharField(choices=[('personalizado', 'Personalizado'), ('gad7', 'GAD-7 (Ansiedad)')], default='personalizado', max_length=20),
        ),
        migrations.AlterField(
            model_name='asignacioncuestionario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='escala',
            field=models.CharField(choices=[('likert4', 'Likert 0 a 3 (Nunca → Siempre)'), ('likert5', 'Likert 0 a 4 (Nunca → Casi siempre)'), ('sino', 'Sí / No'), ('gad7', 'GAD-7 (Nunca → Casi cada día)')], default='likert4', max_length=20),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='respuestacuestionario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='respuestapregunta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
