# Generated by Django 5.2.15 on 2026-06-16 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0004_gad7_subtipo_escala'),
        ('gestion_usuarios', '0003_asignacion_pendiente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionPendiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_pendientes', to='cuestionarios.cuestionario')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_pendientes_dadas', to=settings.AUTH_USER_MODEL)),
                ('invitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_pendientes', to='gestion_usuarios.invitacionpaciente')),
            ],
            options={
                'unique_together': {('invitacion', 'cuestionario')},
            },
        ),
    ]
