# Generated by Django 5.2.15 on 2026-06-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0005_asignacion_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='etiqueta_opcion_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='etiqueta_opcion_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='respuestapregunta',
            name='valor_texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='escala',
            field=models.CharField(choices=[('likert4', 'Likert 0 a 3 (Nunca → Siempre)'), ('likert5', 'Likert 0 a 4 (Nunca → Casi siempre)'), ('sino', 'Sí / No'), ('gad7', 'GAD-7 (Nunca → Casi cada día)'), ('texto', 'Caja de texto (sin puntaje)'), ('binario', 'Etiquetas personalizadas (ej: Triste / Feliz)'), ('fecha', 'Fecha y hora (sin puntaje)'), ('verdadero_falso', 'Verdadero / Falso')], default='likert4', max_length=20),
        ),
        migrations.AlterField(
            model_name='respuestapregunta',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
