# Generated by Django 6.0.6 on 2026-06-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0009_alter_asignacioncuestionario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='subtipo',
            field=models.CharField(choices=[('personalizado', 'Personalizado'), ('gad7', 'GAD-7 (Ansiedad)'), ('pss10', 'PSS-10 (Estrés percibido)'), ('phq9', 'PHQ-9 (Depresión)')], default='personalizado', max_length=20),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='escala',
            field=models.CharField(choices=[('likert4', 'Likert 0 a 3 (Nunca → Siempre)'), ('likert5', 'Likert 0 a 4 (Nunca → Casi siempre)'), ('sino', 'Sí / No'), ('gad7', 'GAD-7 (Nunca → Casi cada día)'), ('pss10', 'PSS-10 (Nunca → Muy a menudo)'), ('phq9', 'PHQ-9 (Ningún día → Casi todos los días)'), ('texto', 'Caja de texto (sin puntaje)'), ('binario', 'Etiquetas personalizadas (ej: Triste / Feliz)'), ('fecha', 'Fecha y hora (sin puntaje)'), ('verdadero_falso', 'Verdadero / Falso')], default='likert4', max_length=20),
        ),
    ]
