# Generated by Django 6.0.6 on 2026-06-30 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0010_alter_cuestionario_subtipo_alter_pregunta_escala'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncuestionario',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuestionarios_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='respuestacuestionario',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to=settings.AUTH_USER_MODEL),
        ),
    ]
