# Generated by Django 6.0.6 on 2026-06-30 15:57

from django.db import migrations, models


def deduplicar_preguntas(apps, schema_editor):
    """
    Elimina preguntas duplicadas (mismo cuestionario + mismo texto) antes de
    aplicar el UniqueConstraint. Conserva la pregunta con el pk más bajo.
    """
    Pregunta = apps.get_model('cuestionarios', 'Pregunta')

    vistos = {}
    a_eliminar = []

    for p in Pregunta.objects.order_by('cuestionario_id', 'texto', 'id'):
        clave = (p.cuestionario_id, p.texto.strip().lower())
        if clave in vistos:
            a_eliminar.append(p.pk)
        else:
            vistos[clave] = p.pk

    if a_eliminar:
        eliminados, _ = Pregunta.objects.filter(pk__in=a_eliminar).delete()
        print(f'\n  [migración] Se eliminaron {eliminados} pregunta(s) duplicada(s).')


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0011_alter_asignacioncuestionario_paciente_and_more'),
    ]

    operations = [
        # 1. Agregar nuevos campos
        migrations.AddField(
            model_name='cuestionario',
            name='id_cuestionario',
            field=models.CharField(blank=True, help_text='Identificador único que asigna el especialista (ej: ANS-001).', max_length=30, null=True, unique=True, verbose_name='ID del cuestionario'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='codigo',
            field=models.CharField(blank=True, help_text='Generado automáticamente (ej: PREG-001).', max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
        # 2. Limpiar duplicados ANTES de crear el constraint
        migrations.RunPython(
            deduplicar_preguntas,
            reverse_code=migrations.RunPython.noop,
        ),
        # 3. Agregar el UniqueConstraint (datos ya limpios)
        migrations.AddConstraint(
            model_name='pregunta',
            constraint=models.UniqueConstraint(fields=('cuestionario', 'texto'), name='pregunta_unica_por_cuestionario'),
        ),
    ]
