# Generated by Django 6.0.6 on 2026-07-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0015_cuestionario_intentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='es_publico',
            field=models.BooleanField(default=False, help_text='Si está activo, todos los especialistas pueden verlo y copiarlo.', verbose_name='Biblioteca pública'),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='borrador', max_length=20),
        ),
    ]
