# Generated by Django 6.0.6 on 2026-06-12 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_usuario_fecha_nacimiento_usuario_motivo_rechazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='numero_registro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='terminos_aceptados_version',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especialistas', to='cuentas.especialidad', verbose_name='Especialidad'),
        ),
    ]
