# Generated by Django 5.2.15 on 2026-06-20 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_especialidad_remove_usuario_numero_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='RegistroAnimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.IntegerField()),
                ('paciente', models.ForeignKey(limit_choices_to={'rol': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='registros_animo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de ánimo',
                'verbose_name_plural': 'Registros de ánimo',
                'ordering': ['-fecha'],
                'unique_together': {('paciente', 'fecha')},
            },
        ),
    ]
