# Generated by Django 6.0.6 on 2026-06-22 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('hora_inicio', models.TimeField(help_text='La pregunta se muestra al paciente a partir de esta hora.')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('especialista', models.ForeignKey(limit_choices_to={'rol': 'especialista'}, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_diarias_configuradas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.OneToOneField(limit_choices_to={'rol': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_diaria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pregunta diaria',
                'verbose_name_plural': 'Preguntas diarias',
            },
        ),
    ]
