# Generated by Django 6.0.6 on 2026-06-22 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_preguntadiaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaPreguntaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('texto', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_pregunta_diaria', to=settings.AUTH_USER_MODEL)),
                ('pregunta_diaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='cuentas.preguntadiaria')),
            ],
            options={
                'verbose_name': 'Respuesta pregunta diaria',
                'verbose_name_plural': 'Respuestas pregunta diaria',
                'ordering': ['-fecha'],
                'unique_together': {('pregunta_diaria', 'fecha')},
            },
        ),
    ]
