# Generated by Django 6.0.6 on 2026-06-22 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_respuestapreguntadiaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordatorioEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('hora', models.TimeField(help_text='Hora a la que se envía el recordatorio.')),
                ('ultimo_envio', models.DateField(blank=True, help_text='Fecha del último envío para evitar duplicados.', null=True)),
                ('paciente', models.OneToOneField(limit_choices_to={'rol': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='recordatorio_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recordatorio por email',
                'verbose_name_plural': 'Recordatorios por email',
            },
        ),
    ]
