# Generated by Django 6.0.6 on 2026-06-25 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_respuestapreguntadiaria'),
        ('cuentas', '0009_recordatorioemail'),
    ]

    operations = [
    ]
