# Generated by Django 6.0.6 on 2026-06-30 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_merge_20260625_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('general', 'General'), ('solicitud_baja_paciente', 'Solicitud de baja (paciente)'), ('solicitud_baja_especialista', 'Solicitud de baja (especialista)')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preguntadiaria',
            name='paciente',
            field=models.OneToOneField(blank=True, limit_choices_to={'rol': 'paciente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pregunta_diaria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recordatorioemail',
            name='paciente',
            field=models.OneToOneField(blank=True, limit_choices_to={'rol': 'paciente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordatorio_email', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registroanimo',
            name='paciente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'paciente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_animo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='respuestapreguntadiaria',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_pregunta_diaria', to=settings.AUTH_USER_MODEL),
        ),
    ]
