# Generated by Django 6.0.6 on 2026-06-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedores', '0002_terminos_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminoscondiciones',
            options={'ordering': ['-version'], 'verbose_name': 'Términos y Condiciones', 'verbose_name_plural': 'Términos y Condiciones'},
        ),
    ]
