# Generated by Django 6.0.6 on 2026-06-12 00:58

import gestion_usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitacionpaciente',
            name='token',
        ),
        migrations.AddField(
            model_name='invitacionpaciente',
            name='pin',
            field=models.CharField(default=gestion_usuarios.models.generar_pin, editable=False, max_length=6),
        ),
    ]
