# Generated by Django 6.0.6 on 2026-06-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_asignacion_pendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacionpaciente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
